name: connector
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^4.0.5345
  flutter_statusbar_text_color: ^0.1.2
  flutter_staggered_animations: ^0.1.2
  shared_preferences: ^0.5.12+4
  cached_network_image: ^2.3.3
  modal_progress_hud: ^0.1.3
  cloud_firestore: ^0.14.3+1
  firebase_auth: ^0.18.3+1
  flutter_offline: ^0.3.0
  cupertino_icons: ^1.0.0
  auto_size_text: ^2.1.0
  firebase_core: ^0.5.3
  provider: ^4.3.2+2
  flushbar: ^1.10.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.png
    - assets/images/Lock.png